# Generated by Django 5.0.1 on 2025-05-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='yookassa_payment_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='YooKassa payment ID'),
        ),
    ]
