# Generated by Django 5.0.1 on 2025-05-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('processing', 'Принят (оплачен)'), ('in_progress', 'В работе'), ('awaiting_shipment', 'Готов к отправке/выдаче'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='status'),
        ),
    ]
