# Generated by Django 5.0.1 on 2025-05-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='site_content/%Y/%m/%d/', verbose_name='image')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which the image appears. Lower numbers appear first.', verbose_name='order')),
            ],
            options={
                'verbose_name': 'About Us Image',
                'verbose_name_plural': 'About Us Images',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroSlideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='site_content/%Y/%m/%d/', verbose_name='image')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which the image appears. Lower numbers appear first.', verbose_name='order')),
            ],
            options={
                'verbose_name': 'Hero Slide Image',
                'verbose_name_plural': 'Hero Slide Images',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='site_content/%Y/%m/%d/', verbose_name='image')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which the image appears. Lower numbers appear first.', verbose_name='order')),
                ('title', models.CharField(blank=True, help_text='Optional title for the work.', max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Optional description for the work.', verbose_name='description')),
                ('link', models.URLField(blank=True, help_text='Optional link related to the work.', verbose_name='link')),
            ],
            options={
                'verbose_name': 'Work Gallery Image',
                'verbose_name_plural': 'Work Gallery Images',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
