# Generated by Django 5.0.1 on 2025-05-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_printingservice_price_per_gram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printingservice',
            name='icon',
        ),
        migrations.AddField(
            model_name='printingservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/', verbose_name='image'),
        ),
    ]
