# Generated by Django 5.0.1 on 2025-05-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Author Name')),
                ('review_text', models.TextField(verbose_name='Review Text')),
                ('source_link', models.URLField(blank=True, help_text='Link to the original review (e.g., Avito)', null=True, verbose_name='Source Link')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating from 1 to 5 stars', null=True, verbose_name='Rating')),
                ('is_visible', models.BooleanField(default=True, help_text='Should this review be displayed on the site?', verbose_name='Is Visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
