# Generated by Django 5.0.1 on 2025-05-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='source_type',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('avito', 'Avito'), ('yandex', 'Yandex Maps'), ('manual', 'Manual Entry'), ('other', 'Other')], default='manual', help_text='Where does this review come from?', max_length=20, verbose_name='Source Type'),
        ),
    ]
