# Generated by Django 5.0.1 on 2025-05-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_source_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='source_type',
        ),
        migrations.AlterField(
            model_name='review',
            name='source_link',
            field=models.URLField(blank=True, help_text='Link to the original review (e.g., Avito, Yandex Maps, etc.)', null=True, verbose_name='Source Link'),
        ),
    ]
